name: yollararo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  # Core Flutter SDK dependency
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0

  # Local database storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Network
  dio: ^5.5.0+1

  # Dependency Injection
  get_it: ^7.7.0

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Routing
  auto_route: ^9.1.0

  # Geolocation services
  geolocator: ^11.1.0

  # Firebase services
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.9

  # UI Widgets
  sliding_up_panel: ^2.0.0+1
  flutter_form_builder: ^9.3.0

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

  # Linting
  flutter_lints: ^4.0.0

  # Code generation
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  auto_route_generator: ^9.0.0

flutter:
  # Use material design icons
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
